name: ba-image-ml
channels:
  - pytorch
  - conda-forge
dependencies:
  # --- Python & Basis ---
  - python=3.10
  - pip

  # --- NumPy/SciPy/Skimage: kompatibel zu Torch 2.0.1 & unseren Libs ---
  - numpy<2
  - scipy>=1.10,<1.16
  - scikit-image=0.25.*

  # --- OpenCV & Basics über conda (vermeidet pip/conda-Konflikte) ---
  - opencv=4.10.*
  - pillow
  - tqdm
  - pyyaml
  - requests

  # --- PyTorch CPU (kleiner, kein CUDA in der VM) ---
  - cpuonly
  - pytorch=2.0.1
  - torchvision=0.15.2

  # --- Rest über pip ---
  - pip:
      - einops
      - lpips
      - pyiqa==0.1.11
      - sewar==0.4.6
      - realesrgan==0.3.0
      - basicsr==1.4.2
      - facexlib==0.3.0
      - gfpgan==1.3.8
