name: ba-image-ml
channels:
  - pytorch
  - conda-forge
dependencies:
  # --- Python & Basis ---
  - python=3.10
  - pip

  # --- NumPy/SciPy/Skimage: kompatibel zu Torch 2.0.1 & den verwendeten Libs ---
  - numpy<2
  - scipy>=1.10,<1.16
  - scikit-image=0.25.*

  # --- OpenCV & Basics über conda (vermeidet pip/conda-Konflikte) ---
  - opencv=4.10.*
  - pillow>=9
  - tqdm
  - pyyaml
  - requests

  # --- PyTorch CPU (kleiner, kein CUDA in der VM) ---
  - cpuonly
  - pytorch=2.0.1
  - torchvision=0.15.2

  # --- Rest über pip ---
  - pip:
      # Utils
      - einops>=0.8
      - matplotlib>=3.10
      - imageio>=2.37
      - tifffile
      - imagecodecs

      # Super-Resolution / Enhancement
      - basicsr==1.4.2
      - realesrgan==0.3.0
      - gfpgan==1.3.8
      - facexlib==0.3.0

      # Image Quality Assessment (IQA)
      - lpips==0.1.4
      - pyiqa==0.1.11
      - piq==0.8.0
      - sewar==0.4.6
      - pybrisque==1.0
