name: ba-image-ml
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # --- Python & Basis ---
  - python=3.10.*
  - pip

  # --- Core via conda ---
  - numpy=1.26.*
  - pandas=2.3.2
  - scipy=1.15.3
  - scikit-image=0.25.*
  - opencv=4.10.*           # conda-Paket heißt 'opencv'
  - pillow=11.*             # 11.x Reihe
  - imageio=2.37.*
  - tifffile=2024.12.12     # kompatibel zu py3.10 & imagecodecs 2024.9.22
  - imagecodecs=2024.9.22
  - matplotlib=3.10.5
  - tqdm
  - pyyaml=6.0.2
  - requests=2.32.5

  # --- PyTorch CPU ---
  - cpuonly
  - pytorch=2.0.1
  - torchvision=0.15.2

  # --- Rest via pip (nur echte Pip-Pakete) ---
  - pip:
      - basicsr==1.4.2
      - realesrgan==0.3.0
      - gfpgan==1.3.8
      - facexlib==0.3.0
      - lpips==0.1.4
      - pyiqa==0.1.11
      - piq==0.8.0
      - sewar==0.4.6
      - pybrisque==1.0
      - einops==0.8.1
      - timm==1.0.19
      - accelerate==1.10.0
